{% set name = "apache-airflow-providers-apprise" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apprise-{{ version }}.tar.gz
  sha256: fb6c8b638c4921888d7241a718ff6a1dbb999de1fdb7d9e089ab2cddb04c8e97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.6.0
    - apprise

test:
  imports:
    - airflow.providers.apprise
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apprise for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apprise/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apprise/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
