{% set name = "apache-airflow-providers-apprise" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apprise-{{ version }}.tar.gz
  sha256: c6a5922fc8f413cd63df93eeedb988608965e62d8a6236a76e9e3e461dc5f4c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.11.0
    - pip
  run:
    - apache-airflow-providers-common-compat >=1.6.0
    - python >={{ python_min }}
    - apache-airflow >=2.9.0
    - apprise >=1.8.0

test:
  imports:
    - airflow.providers.apprise
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apprise for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/apprise/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apprise/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
